// src/react/AccountMenu.tsx
// AccountMenu: the shared account menu for every Latere SPA: identity header,
// optional "Open dashboard", an org list with an explicit Personal (no-org)
// row and each membership, an optional prefs slot (theme/locale), then Sign
// out or Sign in.
//
// It does not require a router. It reads `principal`/`login`/`logout`/
// `switchOrg` from a `<SessionProvider>` ancestor (via `useOptionalSession`)
// when the corresponding prop is omitted, so `<AccountMenu />` alone under a
// provider works; every prop also works standalone, inside a host that keeps
// its own session state.
// Requires `import 'latere-ui/console'` when nested in ConsoleSidebar's foot
// (that sheet carries the `.lu-cs-foot .lu-am-*` size overrides); the menu's
// own styles are self-contained via the import below.
import { useRef, useState, type ReactNode } from 'react';

import type { Principal } from '../session/types';
import '../styles/components/account-menu.css';
import {
  DEFAULT_ACCOUNT_MENU_LABELS,
  identityLine,
  identityParts,
  type AccountMenuItem,
  type AccountMenuLabelOverrides,
  type AccountMenuLabels,
  type AccountMenuSubline,
} from '../components/accountMenu';
import { cx, useClickOutside } from './internal';
import { useOptionalSession } from './session';

export type { AccountMenuLabels, AccountMenuItem };

type Placement = 'top-end' | 'bottom-start';

export interface AccountMenuProps {
  /**
   * The signed-in principal, or `null` when logged out. Omit to read from
   * the ambient `<SessionProvider>` (falls back to `null` with no provider).
   */
  principal?: Principal | null;
  /** `top-end`: top-nav dropdown opening down-right. `bottom-start`: left-rail pill opening up. */
  placement?: Placement;
  /** When set, shows an "Open dashboard" row that calls `onNavigate`. */
  dashboardPath?: string | null;
  /** Org id currently being switched to (`''` = Personal); drives the spinner + dims others. */
  switchingOrgId?: string | null;
  /** When true, render nothing while logged out (instead of a Sign-in CTA). */
  signedInOnly?: boolean;
  /** Per-locale label overrides (deep-partial; `roles` merges over defaults). */
  labels?: AccountMenuLabelOverrides;
  /** Per-app custom rows (e.g. Admin Panel), rendered in the menu's own style. */
  extraItems?: AccountMenuItem[];
  /** Called when a membership/Personal row is picked. Omit to use the ambient provider's `switchOrg`. */
  onSwitchOrg?: (orgId: string) => void;
  /** Called for the dashboard row and `to`-style extra items. */
  onNavigate?: (path: string) => void;
  /** Called on the Sign-in action. Omit to use the ambient provider's `login`. */
  onLogin?: () => void;
  /** Called on the Sign-out action. Omit to use the ambient provider's `logout`. */
  onLogout?: () => void;
  /** Called for `id`-style extra items (pure actions, no `href`/`to`). */
  onItemSelect?: (id: string) => void;
  /** Preferences content (theme/locale pills), rendered in its own section. */
  prefs?: ReactNode;
  /** Escape hatch for fully custom markup, styled to match via `.lu-am-item`. */
  extra?: ReactNode;
  /**
   * How the trigger states the role and account under the name: `badge`
   * (default) sets the role as an uppercase badge beside the organization;
   * `text` sets one quiet line, "Platform admin · Personal"; `role` sets a
   * sentence-case badge, "Platform admin", then the account in quiet text.
   * With `text` and `role` the dropdown's header follows the same case.
   */
  subline?: AccountMenuSubline;
}

export function AccountMenu({
  principal: principalProp,
  placement = 'top-end',
  dashboardPath = null,
  switchingOrgId = null,
  signedInOnly = false,
  labels,
  extraItems = [],
  onSwitchOrg,
  onNavigate,
  onLogin,
  onLogout,
  onItemSelect,
  prefs,
  extra,
  subline = 'badge',
}: AccountMenuProps) {
  const session = useOptionalSession();
  const principal = principalProp !== undefined ? principalProp : (session?.principal ?? null);
  const login = onLogin ?? (session ? () => session.login() : undefined);
  const logout = onLogout ?? (session ? () => session.logout() : undefined);
  const switchOrg =
    onSwitchOrg ?? (session ? (orgId: string) => void session.switchOrg(orgId) : undefined);

  const t: AccountMenuLabels = {
    ...DEFAULT_ACCOUNT_MENU_LABELS,
    ...labels,
    // Deep-merge the roles sub-object so a consumer passing partial role
    // labels doesn't wipe the defaults for the rest.
    roles: { ...DEFAULT_ACCOUNT_MENU_LABELS.roles, ...labels?.roles },
    roleNames: { ...DEFAULT_ACCOUNT_MENU_LABELS.roleNames!, ...labels?.roleNames },
  };

  const hasDropdown = !!principal || !!prefs || !!extra || extraItems.length > 0;

  const [open, setOpen] = useState(false);
  const root = useRef<HTMLDivElement>(null);
  useClickOutside(root, open, () => setOpen(false));

  function onTrigger() {
    if (hasDropdown) setOpen((o) => !o);
    else login?.(); // logged out + nothing to show → straight to login
  }

  const initials = principal?.initials || '?';
  const avatarUrl = principal?.avatar_url || '';
  const name = principal?.display_name || principal?.name || principal?.email || t.account;
  const email = principal?.email || '';
  const orgName = principal?.org_name || '';

  const role = principal?.role;
  const roleBadge = role && role !== 'individual' ? t.roles[role] : '';
  const identitySub = orgName || (role ? t.roles.individual : t.personal);
  // The sentence-case sublines (`text`, `role`) name the role and the
  // account in running text, in the trigger and in the dropdown's header.
  const sentence = subline === 'text' || subline === 'role';
  const parts = identityParts(principal, t);
  const orgs = principal?.orgs ?? [];
  const activeOrgId = principal?.org_id || '';
  const isPersonal = !activeOrgId;

  const opensUp = placement === 'bottom-start';

  function rowOpacity(id: string): number {
    return switchingOrgId !== null && switchingOrgId !== id ? 0.5 : 1;
  }

  function pickOrg(id: string) {
    if (id === activeOrgId || switchingOrgId !== null) return;
    switchOrg?.(id);
  }
  function goto(path: string) {
    setOpen(false);
    onNavigate?.(path);
  }
  function onSignOut() {
    setOpen(false);
    logout?.();
  }
  function onSignIn() {
    setOpen(false);
    login?.();
  }
  function onExtraItem(item: AccountMenuItem) {
    setOpen(false);
    if (item.to) onNavigate?.(item.to);
    else if (item.id) onItemSelect?.(item.id);
  }

  if (!principal && signedInOnly) return null;

  return (
    <div ref={root} className={cx('lu-am', opensUp && 'lu-am-up')} data-subline={subline}>
      <button type="button"
        className="lu-am-trigger"
        onClick={onTrigger}
        aria-expanded={hasDropdown ? open : undefined}
        title={principal ? t.account : t.signIn}
      >
        {/* Avatar always present so the pill keeps its shape; logged out shows
            the "?" initials fallback. */}
        <span className="lu-am-avatar">
          {avatarUrl ? <img src={avatarUrl} alt="" referrerPolicy="no-referrer" /> : <span>{initials}</span>}
        </span>
        <span className="lu-am-id">
          <span className="lu-am-id-name">{principal ? name : t.signIn}</span>
          {/* Sub-label (role badge + org / Individual) only when signed in —
              the logged-out "Sign in" trigger stays a single line. */}
          {principal && subline === 'text' && (
            <span className="lu-am-id-line">{identityLine(principal, t)}</span>
          )}
          {principal && subline === 'role' && (
            <span className="lu-am-id-role">
              {parts.role && (
                <span className={cx('lu-am-role', `lu-am-role-${role}`)}>{parts.role}</span>
              )}
              <span className="lu-am-id-context">{parts.context}</span>
            </span>
          )}
          {principal && subline !== 'text' && subline !== 'role' && (
            <span className="lu-am-id-sub">
              {roleBadge && (
                <span className={cx('lu-am-role', `lu-am-role-${role}`)}>{roleBadge}</span>
              )}
              <span className="lu-am-id-sub-text">{identitySub}</span>
            </span>
          )}
        </span>
        {hasDropdown && (
          <svg
            className="lu-am-chev"
            width="11"
            height="11"
            viewBox="0 0 12 12"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="round"
            aria-hidden="true"
          >
            {opensUp ? <path d="M3 7.5l3-3 3 3" /> : <path d="M3 4.5l3 3 3-3" />}
          </svg>
        )}
      </button>

      {open && hasDropdown && (
        <div className={cx('lu-am-dd', placement === 'top-end' ? 'lu-am-dd-right' : 'lu-am-dd-left')}>
          {/* Identity header */}
          {principal ? (
            <div className="lu-am-head">
              <span className="lu-am-head-avatar">
                {avatarUrl ? (
                  <img src={avatarUrl} alt="" referrerPolicy="no-referrer" />
                ) : (
                  <span>{initials}</span>
                )}
              </span>
              <div className="lu-am-head-text">
                <div className="lu-am-head-name">{name}</div>
                <div className="lu-am-head-email">{email}</div>
                {/* Identity descriptor: the role badge + org/individual context.
                    Triggers may hide these to stay compact, so the dropdown is
                    the canonical place they always resolve. */}
                {sentence ? (
                  <div className="lu-am-head-meta">
                    {parts.role && (
                      <span className={cx('lu-am-role', `lu-am-role-${role}`)}>{parts.role}</span>
                    )}
                    <span className="lu-am-head-context">{parts.context}</span>
                  </div>
                ) : (roleBadge || identitySub) && (
                  <div className="lu-am-head-meta">
                    {roleBadge && (
                      <span className={cx('lu-am-role', `lu-am-role-${role}`)}>{roleBadge}</span>
                    )}
                    <span className="lu-am-head-context">{identitySub}</span>
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="lu-am-head lu-am-head-muted">{t.notSignedIn}</div>
          )}

          {principal && (
            <>
              {/* Dashboard link */}
              {dashboardPath && (
                <div className="lu-am-section">
                  <button type="button" className="lu-am-item" onClick={() => goto(dashboardPath)}>
                    <span>{t.openDashboard}</span>
                  </button>
                </div>
              )}

              {/* Organizations — only when the principal actually has memberships, so
                  a degraded /api/me (orgs fetch failed) doesn't show a lonely Personal. */}
              {orgs.length > 0 && (
                <div className="lu-am-section">
                  <div className="lu-am-section-label">{t.organizations}</div>

                  {/* Personal (no-org): present so the user can switch back. */}
                  <button type="button"
                    className={cx('lu-am-item', 'lu-am-org', isPersonal && 'is-active')}
                    style={{ opacity: rowOpacity('') }}
                    onClick={() => pickOrg('')}
                  >
                    <span className="lu-am-org-mark">{initials}</span>
                    <span className="lu-am-org-text">
                      <span className="lu-am-org-name">{t.personal}</span>
                      <span className="lu-am-org-meta">{t.noOrganization}</span>
                    </span>
                    {isPersonal ? (
                      <svg
                        className="lu-am-check"
                        width="13"
                        height="13"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        aria-hidden="true"
                      >
                        <path d="M5 12l5 5L20 6" />
                      </svg>
                    ) : (
                      switchingOrgId === '' && <span className="lu-am-spin">…</span>
                    )}
                  </button>

                  {orgs.map((o) => (
                    <button type="button"
                      key={o.id}
                      className={cx('lu-am-item', 'lu-am-org', o.id === activeOrgId && 'is-active')}
                      style={{ opacity: rowOpacity(o.id) }}
                      onClick={() => pickOrg(o.id)}
                    >
                      <span className="lu-am-org-mark lu-am-org-team">
                        {(o.name || o.id).slice(0, 2).toUpperCase()}
                      </span>
                      <span className="lu-am-org-text">
                        <span className="lu-am-org-name">
                          {`${o.name || o.id}${o.owner ? ' ' : ''}`}
                          {o.owner && <span className="lu-am-owner">{t.owner}</span>}
                        </span>
                        {o.slug && <span className="lu-am-org-meta">{`@${o.slug}`}</span>}
                      </span>
                      {o.id === activeOrgId ? (
                        <svg
                          className="lu-am-check"
                          width="13"
                          height="13"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2.5"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          aria-hidden="true"
                        >
                          <path d="M5 12l5 5L20 6" />
                        </svg>
                      ) : (
                        switchingOrgId === o.id && <span className="lu-am-spin">…</span>
                      )}
                    </button>
                  ))}
                </div>
              )}
            </>
          )}

          {/* App-provided preferences (theme / locale pills). */}
          {prefs && <div className="lu-am-section">{prefs}</div>}

          {/* Per-app custom rows (data-driven; styled in this component so they
              always match). Links render as <a>, router paths call onNavigate,
              pure actions call onItemSelect. */}
          {extraItems.length > 0 && (
            <div className="lu-am-section">
              {extraItems.map((item, i) =>
                item.href ? (
                  <a
                    key={item.id || item.href || item.to || i}
                    className={cx('lu-am-item', item.danger && 'lu-am-danger')}
                    href={item.href}
                    target={item.target}
                    rel={item.target === '_blank' ? 'noopener' : undefined}
                    onClick={() => setOpen(false)}
                  >
                    <span>{item.label}</span>
                  </a>
                ) : (
                  <button type="button"
                    key={item.id || item.href || item.to || i}
                    className={cx('lu-am-item', item.danger && 'lu-am-danger')}
                    onClick={() => onExtraItem(item)}
                  >
                    <span>{item.label}</span>
                  </button>
                ),
              )}
            </div>
          )}

          {/* Escape hatch for fully-custom markup. */}
          {extra && <div className="lu-am-section">{extra}</div>}

          <div className="lu-am-section">
            {principal ? (
              <button type="button" className="lu-am-item lu-am-danger" onClick={onSignOut}>
                <span>{t.signOut}</span>
              </button>
            ) : (
              <button type="button" className="lu-am-item" onClick={onSignIn}>
                <span>{t.signIn}</span>
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// src/components/AccountMenu.vue
<script setup lang="ts">
// Shared account menu for every Latere SPA. Modeled on lux's UserOrgMenu (the
// most comprehensive): identity header → optional "Open dashboard" → an org
// list with an explicit Personal (no-org) row and each membership (owner
// badge, slug, active check, per-row switch spinner that dims the others) →
// an optional prefs slot (theme/locale) → Sign out / Sign in.
//
// Decoupled: it imports neither the session store nor vue-router. Org rows
// emit `switch-org`, the dashboard row emits `navigate`, and auth actions emit
// `login`/`logout`; the host wires those to its store + router. Self-contained
// trigger + dropdown with scoped styles, so consumers get consistent layout
// with no CSS import. Relies on the platform CSS tokens (--text, --bg-raised,
// --accent, …) that every app already defines.
import { computed, ref, useSlots } from 'vue';

import '../styles/components/account-menu.css';
import type { Principal } from '../session/types';
import { useClickOutside } from '../composables/useClickOutside';
import {
  type AccountMenuLabels,
  type AccountMenuLabelOverrides,
  type AccountMenuItem,
  type AccountMenuSubline,
  DEFAULT_ACCOUNT_MENU_LABELS,
  identityLine,
  identityParts,
} from './accountMenu';

export type { AccountMenuLabels, AccountMenuItem };

type Placement = 'top-end' | 'bottom-start';

const DEFAULT_LABELS = DEFAULT_ACCOUNT_MENU_LABELS;

const props = withDefaults(
  defineProps<{
    /** The signed-in principal, or null when logged out. */
    principal: Principal | null;
    /** `top-end`: top-nav dropdown opening down-right. `bottom-start`: left-rail pill opening up. */
    placement?: Placement;
    /** When set, shows an "Open dashboard" row that emits `navigate`. */
    dashboardPath?: string | null;
    /** Org id currently being switched to ('' = Personal); drives the spinner + dims others. */
    switchingOrgId?: string | null;
    /** When true, render nothing while logged out (instead of a Sign-in CTA). */
    signedInOnly?: boolean;
    /** Per-locale label overrides (deep-partial; roles merge over defaults). */
    labels?: AccountMenuLabelOverrides;
    /**
     * Per-app custom rows (e.g. Admin Panel) rendered in the menu's own style,
     * between the prefs and Sign out. Prefer this over the #extra slot, whose
     * slotted markup can't pick up the scoped item styles.
     */
    extraItems?: AccountMenuItem[];
    /**
     * How the trigger states the role and account under the name: `badge`
     * (default) sets the role as an uppercase badge beside the organization;
     * `text` sets one quiet line, "Platform admin · Personal"; `role` sets a
     * sentence-case badge, "Platform admin", then the account in quiet text.
     * With `text` and `role` the dropdown's header follows the same case.
     */
    subline?: AccountMenuSubline;
  }>(),
  {
    subline: 'badge',
    placement: 'top-end',
    dashboardPath: null,
    switchingOrgId: null,
    signedInOnly: false,
    labels: undefined,
    extraItems: () => [],
  },
);

const emit = defineEmits<{
  (e: 'switch-org', orgId: string): void;
  (e: 'navigate', path: string): void;
  (e: 'login'): void;
  (e: 'logout'): void;
  (e: 'item-select', id: string): void;
}>();

const t = computed<AccountMenuLabels>(() => ({
  ...DEFAULT_LABELS,
  ...props.labels,
  // Deep-merge the roles sub-object so a consumer passing partial role
  // labels doesn't wipe the defaults for the rest.
  roles: { ...DEFAULT_LABELS.roles, ...props.labels?.roles },
  roleNames: { ...DEFAULT_LABELS.roleNames!, ...props.labels?.roleNames },
}));

const slots = useSlots();
// A dropdown is only worth opening when it has content: the signed-in
// surface (identity + orgs + sign out), or app-provided prefs/extra/items.
// When logged out with none of those, the trigger is a plain "Log in" button
// (no dropdown, no chevron) — avoids the empty "Not signed in" panel.
const hasDropdown = computed(
  () => !!props.principal || !!slots.prefs || !!slots.extra || props.extraItems.length > 0,
);

const open = ref(false);
const root = ref<HTMLElement | null>(null);
useClickOutside(
  root,
  () => open.value,
  () => (open.value = false),
);

function onTrigger() {
  if (hasDropdown.value) open.value = !open.value;
  else emit('login'); // logged out + nothing to show → straight to login
}

const me = computed(() => props.principal);
const initials = computed(() => me.value?.initials || '?');
const avatarUrl = computed(() => me.value?.avatar_url || '');
const name = computed(
  () => me.value?.display_name || me.value?.name || me.value?.email || t.value.account,
);
const email = computed(() => me.value?.email || '');
const orgName = computed(() => me.value?.org_name || '');

// Canonical role badge (shared four-role account model). The subline text
// carries the org context ("Individual" for a no-org principal); the badge
// names the role. `individual` needs no badge — the subline already says it.
const role = computed(() => me.value?.role);
const roleBadge = computed(() =>
  role.value && role.value !== 'individual' ? t.value.roles[role.value] : '',
);
// Subline: the org name when in an org, otherwise the role-aware personal
// label ("Individual") when a role is set, falling back to the legacy
// "Personal" string for consumers that don't pass a role.
const identitySub = computed(() => {
  if (orgName.value) return orgName.value;
  if (role.value) return t.value.roles.individual;
  return t.value.personal;
});
// The sentence-case sublines (`text`, `role`) name the role and the account
// in running text, in the trigger and in the dropdown's header alike.
const sentence = computed(() => props.subline === 'text' || props.subline === 'role');
const parts = computed(() => identityParts(me.value, t.value));
const orgs = computed(() => me.value?.orgs ?? []);
const activeOrgId = computed(() => me.value?.org_id || '');
const isPersonal = computed(() => !activeOrgId.value);

const opensUp = computed(() => props.placement === 'bottom-start');

function rowOpacity(id: string): number {
  const s = props.switchingOrgId;
  return s !== null && s !== id ? 0.5 : 1;
}

function pickOrg(id: string) {
  if (id === activeOrgId.value || props.switchingOrgId !== null) return;
  emit('switch-org', id);
}
function goto(path: string) {
  open.value = false;
  emit('navigate', path);
}
function onSignOut() {
  open.value = false;
  emit('logout');
}
function onSignIn() {
  open.value = false;
  emit('login');
}
function onExtraItem(item: AccountMenuItem) {
  // Only reached from the `<button type="button" v-else>` branch (rendered when !item.href);
  // href rows go through the native `<a>` branch, which never calls this.
  open.value = false;
  if (item.to) emit('navigate', item.to);
  else if (item.id) emit('item-select', item.id);
}
</script>

<template>
  <div
    v-if="principal || !signedInOnly"
    class="lu-am"
    :class="{ 'lu-am-up': opensUp }"
    :data-subline="subline"
    ref="root"
  >
    <button type="button"
      class="lu-am-trigger"
      @click="onTrigger"
      :aria-expanded="hasDropdown ? open : undefined"
      :title="principal ? t.account : t.signIn"
    >
      <!-- Avatar always present so the pill keeps its shape; logged out shows
           the "?" initials fallback. -->
      <span class="lu-am-avatar">
        <img v-if="avatarUrl" :src="avatarUrl" alt="" referrerpolicy="no-referrer" />
        <span v-else>{{ initials }}</span>
      </span>
      <span class="lu-am-id">
        <span class="lu-am-id-name">{{ principal ? name : t.signIn }}</span>
        <!-- Sub-label (role badge + org / Individual) only when signed in —
             the logged-out "Sign in" trigger stays a single line. -->
        <span v-if="principal && subline === 'text'" class="lu-am-id-line">{{ identityLine(principal, t) }}</span>
        <span v-else-if="principal && subline === 'role'" class="lu-am-id-role">
          <span
            v-if="parts.role"
            class="lu-am-role"
            :class="`lu-am-role-${role}`"
          >{{ parts.role }}</span>
          <span class="lu-am-id-context">{{ parts.context }}</span>
        </span>
        <span class="lu-am-id-sub" v-else-if="principal">
          <span
            v-if="roleBadge"
            class="lu-am-role"
            :class="`lu-am-role-${role}`"
          >{{ roleBadge }}</span>
          <span class="lu-am-id-sub-text">{{ identitySub }}</span>
        </span>
      </span>
      <svg
        v-if="hasDropdown"
        class="lu-am-chev"
        width="11"
        height="11"
        viewBox="0 0 12 12"
        fill="none"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="round"
        aria-hidden="true"
      >
        <path v-if="opensUp" d="M3 7.5l3-3 3 3" />
        <path v-else d="M3 4.5l3 3 3-3" />
      </svg>
    </button>

    <div v-if="open && hasDropdown" class="lu-am-dd" :class="placement === 'top-end' ? 'lu-am-dd-right' : 'lu-am-dd-left'">
      <!-- Identity header -->
      <div class="lu-am-head" v-if="principal">
        <span class="lu-am-head-avatar">
          <img v-if="avatarUrl" :src="avatarUrl" alt="" referrerpolicy="no-referrer" />
          <span v-else>{{ initials }}</span>
        </span>
        <div class="lu-am-head-text">
          <div class="lu-am-head-name">{{ name }}</div>
          <div class="lu-am-head-email">{{ email }}</div>
          <!-- Identity descriptor: the role badge + org/individual context.
               Triggers may hide these to stay compact, so the dropdown is the
               canonical place they always resolve. -->
          <div v-if="sentence" class="lu-am-head-meta">
            <span
              v-if="parts.role"
              class="lu-am-role"
              :class="`lu-am-role-${role}`"
            >{{ parts.role }}</span>
            <span class="lu-am-head-context">{{ parts.context }}</span>
          </div>
          <div v-else-if="roleBadge || identitySub" class="lu-am-head-meta">
            <span
              v-if="roleBadge"
              class="lu-am-role"
              :class="`lu-am-role-${role}`"
            >{{ roleBadge }}</span>
            <span class="lu-am-head-context">{{ identitySub }}</span>
          </div>
        </div>
      </div>
      <div class="lu-am-head lu-am-head-muted" v-else>{{ t.notSignedIn }}</div>

      <template v-if="principal">
        <!-- Dashboard link -->
        <div v-if="dashboardPath" class="lu-am-section">
          <button type="button" class="lu-am-item" @click="goto(dashboardPath)">
            <span>{{ t.openDashboard }}</span>
          </button>
        </div>

        <!-- Organizations — only when the principal actually has memberships, so
             a degraded /api/me (orgs fetch failed) doesn't show a lonely Personal. -->
        <div v-if="orgs.length" class="lu-am-section">
          <div class="lu-am-section-label">{{ t.organizations }}</div>

          <!-- Personal (no-org): present so the user can switch back. -->
          <button type="button"
            class="lu-am-item lu-am-org"
            :class="{ 'is-active': isPersonal }"
            :style="{ opacity: rowOpacity('') }"
            @click="pickOrg('')"
          >
            <span class="lu-am-org-mark">{{ initials }}</span>
            <span class="lu-am-org-text">
              <span class="lu-am-org-name">{{ t.personal }}</span>
              <span class="lu-am-org-meta">{{ t.noOrganization }}</span>
            </span>
            <svg
              v-if="isPersonal"
              class="lu-am-check"
              width="13"
              height="13"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2.5"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path d="M5 12l5 5L20 6" />
            </svg>
            <span v-else-if="switchingOrgId === ''" class="lu-am-spin">…</span>
          </button>

          <button type="button"
            v-for="o in orgs"
            :key="o.id"
            class="lu-am-item lu-am-org"
            :class="{ 'is-active': o.id === activeOrgId }"
            :style="{ opacity: rowOpacity(o.id) }"
            @click="pickOrg(o.id)"
          >
            <span class="lu-am-org-mark lu-am-org-team">{{ (o.name || o.id).slice(0, 2).toUpperCase() }}</span>
            <span class="lu-am-org-text">
              <span class="lu-am-org-name">
                {{ o.name || o.id }}
                <span v-if="o.owner" class="lu-am-owner">{{ t.owner }}</span>
              </span>
              <span v-if="o.slug" class="lu-am-org-meta">@{{ o.slug }}</span>
            </span>
            <svg
              v-if="o.id === activeOrgId"
              class="lu-am-check"
              width="13"
              height="13"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2.5"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path d="M5 12l5 5L20 6" />
            </svg>
            <span v-else-if="switchingOrgId === o.id" class="lu-am-spin">…</span>
          </button>
        </div>
      </template>

      <!-- App-provided preferences (theme / locale pills). -->
      <div v-if="$slots.prefs" class="lu-am-section">
        <slot name="prefs" />
      </div>

      <!-- Per-app custom rows (data-driven; styled in this component's scope so
           they always match). Links render as <a>, router paths emit navigate,
           pure actions emit item-select. -->
      <div v-if="extraItems.length" class="lu-am-section">
        <template v-for="(item, i) in extraItems" :key="item.id || item.href || item.to || i">
          <a
            v-if="item.href"
            class="lu-am-item"
            :class="{ 'lu-am-danger': item.danger }"
            :href="item.href"
            :target="item.target"
            :rel="item.target === '_blank' ? 'noopener' : undefined"
            @click="open = false"
          >
            <span>{{ item.label }}</span>
          </a>
          <button type="button"
            v-else
            class="lu-am-item"
            :class="{ 'lu-am-danger': item.danger }"
            @click="onExtraItem(item)"
          >
            <span>{{ item.label }}</span>
          </button>
        </template>
      </div>

      <!-- Escape hatch for fully-custom markup. Slotted content is styled via
           :slotted(.lu-am-item) below so it still matches the menu. -->
      <div v-if="$slots.extra" class="lu-am-section">
        <slot name="extra" />
      </div>

      <div class="lu-am-section">
        <button type="button" v-if="principal" class="lu-am-item lu-am-danger" @click="onSignOut">
          <span>{{ t.signOut }}</span>
        </button>
        <button type="button" v-else class="lu-am-item" @click="onSignIn">
          <span>{{ t.signIn }}</span>
        </button>
      </div>
    </div>
  </div>
</template>
