// src/react/ConsolePalette.tsx
import { useEffect, useId, useMemo, useRef, useState, type KeyboardEvent } from 'react';
import { createPortal } from 'react-dom';
import type { ConsoleNavModel, NavItem } from '../console/nav';
import { consoleIcon } from '../console/icons';
import { filterPalette, paletteEntries, type ConsolePaletteItem, type ConsolePaletteSearch } from '../console/palette';
import { ConsoleIcon } from './ConsoleIcon';
import { useFocusTrap } from './internal';
import '../styles/components/console-palette.css';

export interface ConsolePaletteProps {
  open: boolean;
  model: ConsoleNavModel;
  placeholder?: string;
  emptyLabel?: string;
  onClose?: () => void;
  /** Called with the chosen row: a nav row, a host entry or a search result. */
  onNavigate?: (item: NavItem) => void;
  /** Host entries after the nav rows: actions and other destinations. */
  items?: ConsolePaletteItem[];
  /** Extra rows for a non-empty query, such as documentation pages. */
  search?: ConsolePaletteSearch;
}

export function ConsolePalette({ open, model, placeholder = 'Jump to…', emptyLabel = 'No matches', onClose, onNavigate, items: extra, search }: ConsolePaletteProps) {
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState(0);
  const panel = useRef<HTMLDivElement>(null);
  const id = useId();
  const items = useMemo(() => paletteEntries(model.groups, extra), [model.groups, extra]);
  const results = useMemo(() => filterPalette(items, query, search), [items, query, search]);
  useFocusTrap(open, panel, onClose);
  useEffect(() => { if (open) { setQuery(''); setSelected(0); } }, [open]);
  useEffect(() => { setSelected(0); }, [results]);
  useEffect(() => {
    if (open) panel.current?.querySelector('[data-active="true"]')?.scrollIntoView({ block: 'nearest' });
  }, [open, results, selected]);
  function choose(item: NavItem) { onNavigate?.(item); onClose?.(); }
  function onKeydown(event: KeyboardEvent<HTMLInputElement>) {
    if (event.key === 'ArrowDown') {
      event.preventDefault(); setSelected(value => Math.max(0, Math.min(value + 1, results.length - 1)));
    } else if (event.key === 'ArrowUp') {
      event.preventDefault(); setSelected(value => Math.max(0, value - 1));
    } else if (event.key === 'Enter') {
      event.preventDefault(); if (results[selected]) choose(results[selected]);
    }
  }
  if (!open || typeof document === 'undefined') return null;
  return createPortal(<div className="lu-cp-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose?.(); }}>
    <div ref={panel} className="lu-cp" role="dialog" aria-modal="true" aria-label={placeholder}>
      <input className="lu-cp-input" type="text" role="combobox" aria-expanded="true" aria-label={placeholder} aria-controls={`${id}-list`} aria-activedescendant={results.length ? `${id}-option-${selected}` : undefined} placeholder={placeholder} value={query} onChange={event => setQuery(event.target.value)} onKeyDown={onKeydown} />
      <ul id={`${id}-list`} className="lu-cp-list" role="listbox">
        {results.map((item, index) => <li key={item.id} id={`${id}-option-${index}`} className="lu-cp-item" data-active={index === selected ? 'true' : 'false'} role="option" aria-selected={index === selected} onMouseEnter={() => setSelected(index)} onClick={() => choose(item)}>
          {consoleIcon(item.icon) && <span className="lu-cp-item-icon"><ConsoleIcon name={item.icon!} /></span>}
          <span className="lu-cp-item-label">{item.label}</span>{item.group && <span className="lu-cp-item-group">{item.group}</span>}
        </li>)}
        {!results.length && <li className="lu-cp-empty">{emptyLabel}</li>}
      </ul>
    </div>
  </div>, document.body);
}

// src/components/ConsolePalette.vue
<script setup lang="ts">
// Shared command palette: a ⌘K overlay over the console's nav rows, sub-pages
// included, the host's own entries (actions and other destinations) and, for a
// query, the rows the host's search returns. Matching lives in
// console/palette.ts so the React adapter lists the same rows. Apps with
// richer command systems (e.g. cella) keep their own; the rest wire
// ConsoleSidebar's `search` event to this.

import { computed, ref, watch, useId } from 'vue';

import type { ConsoleNavModel, NavItem } from '../console/nav';
import { consoleIcon } from '../console/icons';
import { filterPalette, paletteEntries, type ConsolePaletteItem, type ConsolePaletteSearch } from '../console/palette';
import { useFocusTrap } from '../glass/overlay';
import ConsoleIcon from './ConsoleIcon.vue';

interface Props {
  open: boolean;
  model: ConsoleNavModel;
  placeholder?: string;
  emptyLabel?: string;
  /** Host entries after the nav rows: actions and other destinations. */
  items?: ConsolePaletteItem[];
  /** Extra rows for a non-empty query, such as documentation pages. */
  search?: ConsolePaletteSearch;
}
const props = withDefaults(defineProps<Props>(), {
  placeholder: 'Jump to…',
  emptyLabel: 'No matches',
});

const emit = defineEmits<{ close: []; navigate: [NavItem] }>();

const query = ref('');
const selected = ref(0);
const inputEl = ref<HTMLInputElement | null>(null);
const panel = ref<HTMLElement | null>(null);
const id = useId();
useFocusTrap({ active: computed(() => props.open), container: panel, initialFocus: inputEl, onEscape: () => emit('close') });

// Routable, enabled nav rows, then the host's entries; a query also runs the
// host's search.
const items = computed(() => paletteEntries(props.model.groups, props.items));
const results = computed(() => filterPalette(items.value, query.value, props.search));

watch(
  () => props.open,
  (open) => {
    if (open) {
      query.value = '';
      selected.value = 0;
    }
  },
);
watch(results, () => {
  selected.value = 0;
});
watch([selected, results, () => props.open], () => {
  if (props.open) panel.value?.querySelector('[data-active="true"]')?.scrollIntoView({ block: 'nearest' });
}, { flush: 'post' });

function choose(item: NavItem) {
  emit('navigate', item);
  emit('close');
}
function onKeydown(e: KeyboardEvent) {
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    selected.value = Math.max(0, Math.min(selected.value + 1, results.value.length - 1));
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    selected.value = Math.max(selected.value - 1, 0);
  } else if (e.key === 'Enter') {
    e.preventDefault();
    const item = results.value[selected.value];
    if (item) choose(item);
  }
}
</script>

<template>
  <Teleport to="body">
    <div v-if="open" class="lu-cp-backdrop" @mousedown.self="emit('close')">
      <div ref="panel" class="lu-cp" role="dialog" aria-modal="true" :aria-label="placeholder">
        <input
          ref="inputEl"
          v-model="query"
          class="lu-cp-input"
          type="text"
          role="combobox"
          aria-expanded="true"
          :aria-label="placeholder"
          :aria-controls="`${id}-list`"
          :aria-activedescendant="results.length ? `${id}-option-${selected}` : undefined"
          :placeholder="placeholder"
          @keydown="onKeydown"
        />
        <ul :id="`${id}-list`" class="lu-cp-list" role="listbox">
          <li
            v-for="(item, i) in results"
            :key="item.id"
            :id="`${id}-option-${i}`"
            class="lu-cp-item"
            :data-active="i === selected ? 'true' : 'false'"
            role="option"
            :aria-selected="i === selected ? 'true' : 'false'"
            @mouseenter="selected = i"
            @click="choose(item)"
          >
            <span v-if="consoleIcon(item.icon)" class="lu-cp-item-icon"><ConsoleIcon :name="item.icon!" /></span>
            <span class="lu-cp-item-label">{{ item.label }}</span>
            <span v-if="item.group" class="lu-cp-item-group">{{ item.group }}</span>
          </li>
          <li v-if="!results.length" class="lu-cp-empty">{{ emptyLabel }}</li>
        </ul>
      </div>
    </div>
  </Teleport>
</template>

<style src="../styles/components/console-palette.css"></style>
