// src/react/DocsLayout.tsx
import { createElement, forwardRef, useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState, type ReactNode } from 'react';
import { adjacentDocs, docPath, findDoc, type DocGroup, type FlatDoc } from '../docs/model';
import { createTocCore, type TocCore, type TocItem, type TocSnapshot } from '../docs/tocCore';
import type { RouterLinkComponent } from './ConsoleSidebar';

export interface DocsLayoutProps {
  groups: DocGroup[];
  activeSlug: string;
  activeGroupId?: string;
  articleHtml?: string;
  articleTitle?: string;
  routerLink?: RouterLinkComponent;
  base?: string;
  showToc?: boolean;
  tocLevels?: number[];
  enhance?: (element: HTMLElement) => void;
  eyebrow?: string;
  tocLabel?: string;
  prevLabel?: string;
  nextLabel?: string;
  sidebarHead?: ReactNode;
  renderGroupIcon?: (group: DocGroup) => ReactNode;
  article?: ReactNode;
  renderToc?: (state: { items: TocItem[]; activeId: string }) => ReactNode;
  onNavigate?: (doc: FlatDoc) => void;
  onTocSelect?: (id: string) => void;
}
export interface DocsLayoutHandle { refresh: () => void; toc: TocCore; }

/** In-app docs shell. Import `latere-ui/docs` for its shared layout styles. */
export const DocsLayout = forwardRef<DocsLayoutHandle, DocsLayoutProps>(function DocsLayout({
  groups, activeSlug, activeGroupId, articleHtml, articleTitle, routerLink, base = '', showToc = true, tocLevels,
  enhance, eyebrow = 'Docs', tocLabel = 'On this page', prevLabel = 'Previous', nextLabel = 'Next',
  sidebarHead, renderGroupIcon, article, renderToc, onNavigate, onTocSelect,
}, ref) {
  const articleRef = useRef<HTMLElement>(null);
  // Preserve enhanced DOM and assigned heading IDs when only TOC state changes.
  const htmlBody = useMemo(() => <div className="lu-docs-body" dangerouslySetInnerHTML={{ __html: articleHtml ?? '' }} />, [articleHtml]);
  const [outline, setOutline] = useState<TocSnapshot>({ items: [], activeId: '' });
  const levelsKey = (tocLevels ?? [2, 3]).join(',');
  const toc = useMemo(() => createTocCore({ levels: levelsKey ? levelsKey.split(',').map(Number) : [] }, setOutline), [levelsKey]);
  const current = findDoc(groups, activeSlug, activeGroupId);
  const heading = articleTitle ?? current?.title ?? '';
  const adjacent = adjacentDocs(groups, activeSlug, activeGroupId);
  const refresh = useCallback(() => {
    const element = articleRef.current;
    if (!element) return;
    enhance?.(element);
    if (showToc) toc.scan(element); else toc.dispose();
  }, [enhance, showToc, toc]);
  useEffect(() => { refresh(); return toc.dispose; }, [refresh, toc, articleHtml, activeSlug, activeGroupId, heading, article]);
  useImperativeHandle(ref, () => ({ refresh, toc }), [refresh, toc]);
  function link(groupId: string, slug: string, props: Record<string, unknown>, children: ReactNode) {
    const path = docPath(groupId, slug, base);
    return createElement(routerLink ?? 'a', { ...(routerLink ? { to: path } : { href: path }), ...props }, children);
  }
  function pager(doc: FlatDoc, direction: 'prev' | 'next') {
    return link(doc.groupId, doc.slug, { className: `lu-docs-pager-link lu-docs-pager-${direction}`, onClick: () => onNavigate?.(doc) }, <><span className="lu-docs-pager-dir">{direction === 'prev' ? prevLabel : nextLabel}</span><span className="lu-docs-pager-title">{doc.title}</span></>);
  }
  return <div className="lu-docs-frame"><div className="lu-docs">
    <aside className="lu-docs-side">
      {sidebarHead ?? <div className="lu-docs-eyebrow">{eyebrow}</div>}
      <nav className="lu-docs-nav">{groups.map(group => <div key={group.id} className="lu-docs-group" data-advanced={group.advanced ? 'true' : 'false'}>
        <div className="lu-docs-group-label">{renderGroupIcon?.(group)}<span>{group.label}</span></div>
        {group.pages.map(page => {
          const active = page.slug === activeSlug && (activeGroupId === undefined || activeGroupId === group.id);
          return link(group.id, page.slug, { key: page.slug, className: 'lu-docs-link', 'data-active': active ? 'true' : 'false', 'data-advanced': page.advanced ? 'true' : 'false', 'aria-current': active ? 'page' : undefined, onClick: () => { const doc = findDoc(groups, page.slug, group.id); if (doc) onNavigate?.(doc); } }, <><span className="lu-docs-link-label">{page.title}</span>{page.badge !== undefined && <span className="lu-docs-link-badge">{page.badge}</span>}</>);
        })}
      </div>)}</nav>
    </aside>
    <main className="lu-docs-main">
      <article ref={articleRef} className="lu-docs-article">{heading && <h1 className="lu-docs-title">{heading}</h1>}{article ?? htmlBody}</article>
      {(adjacent.prev || adjacent.next) && <nav className="lu-docs-pager">{adjacent.prev ? pager(adjacent.prev, 'prev') : <span />}{adjacent.next && pager(adjacent.next, 'next')}</nav>}
    </main>
    {showToc && <aside className="lu-docs-toc">{renderToc ? renderToc(outline) : !!outline.items.length && <div className="lu-docs-toc-inner">
      <div className="lu-docs-toc-label">{tocLabel}</div>
      {outline.items.map(item => <a key={item.id} href={`#${item.id}`} className="lu-docs-toc-link" data-level={item.level} data-active={outline.activeId === item.id ? 'true' : 'false'} onClick={() => { toc.setActive(item.id); onTocSelect?.(item.id); }}>{item.text}</a>)}
    </div>}</aside>}
  </div></div>;
});

// src/components/DocsLayout.vue
<script setup lang="ts">
// Shared in-app docs shell: a grouped doc index (left) · the article (center)
// · an auto table of contents (right) · prev/next across the flattened reading
// order. Works for both markdown docs (pass `articleHtml`) and component-driven
// docs (use the #article slot, as the document-intelligence console does).
//
// The grouped model and TOC scroll-spy are headless (src/docs/*); this is the
// Vue adapter. App-specific post-processing — mermaid, light/dark images,
// `[[diagram:name]]` mounts — plugs into the `enhance` hook; the layout never
// owns a diagram pipeline. Styles ship as `latere-ui/docs` (prefix `lu-docs-`).

import {
  computed,
  nextTick,
  onBeforeUnmount,
  onMounted,
  ref,
  watch,
  type Component,
} from 'vue';

import {
  adjacentDocs,
  docPath,
  findDoc,
  type DocGroup,
  type FlatDoc,
} from '../docs/model';
import { createToc } from '../docs/toc';

interface Props {
  /** Grouped document index. */
  groups: DocGroup[];
  /** Active page slug. */
  activeSlug: string;
  /** Disambiguate when the same slug appears in multiple groups. */
  activeGroupId?: string;
  /** Rendered markdown body (v-html). Omit to use the #article slot. */
  articleHtml?: string;
  /** Title above the body. Defaults to the active page's title. */
  articleTitle?: string;
  /** Injected RouterLink; falls back to a plain `<a>` off-router. */
  routerLink?: Component;
  /** Route base used to build nav hrefs (`<base>/<group>/<slug>`). */
  base?: string;
  /** Render the right-hand TOC. */
  showToc?: boolean;
  /** Heading levels included in the TOC. */
  tocLevels?: number[];
  /**
   * Called with the article element after every (re)render, before the TOC is
   * scanned. Plug in app-specific enhancement (diagrams, image rewriting).
   */
  enhance?: (el: HTMLElement) => void;
  // Copy overrides.
  eyebrow?: string;
  tocLabel?: string;
  prevLabel?: string;
  nextLabel?: string;
}

const props = withDefaults(defineProps<Props>(), {
  base: '',
  showToc: true,
  eyebrow: 'Docs',
  tocLabel: 'On this page',
  prevLabel: 'Previous',
  nextLabel: 'Next',
});

const emit = defineEmits<{
  navigate: [doc: FlatDoc];
  'toc-select': [id: string];
}>();

const articleRef = ref<HTMLElement | null>(null);
const toc = createToc({ levels: props.tocLevels });

const currentDoc = computed(() =>
  findDoc(props.groups, props.activeSlug, props.activeGroupId),
);
const heading = computed(() => props.articleTitle ?? currentDoc.value?.title ?? '');
const adjacent = computed(() =>
  adjacentDocs(props.groups, props.activeSlug, props.activeGroupId),
);

function isActive(group: DocGroup, slug: string): boolean {
  return (
    slug === props.activeSlug &&
    (props.activeGroupId === undefined || group.id === props.activeGroupId)
  );
}

function hrefFor(groupId: string, slug: string): string {
  return docPath(groupId, slug, props.base);
}

function rowTag(): Component | string {
  return props.routerLink ?? 'a';
}
function rowBind(groupId: string, slug: string): Record<string, unknown> {
  const target = hrefFor(groupId, slug);
  return props.routerLink ? { to: target } : { href: target };
}

function onNavigate(doc: FlatDoc | null) {
  if (doc) emit('navigate', doc);
}
function onTocClick(id: string) {
  toc.setActive(id);
  emit('toc-select', id);
}

// Re-run enhancement + TOC scan whenever the rendered body changes.
function refresh() {
  const el = articleRef.value;
  if (!el) return;
  props.enhance?.(el);
  if (props.showToc) toc.scan(el);
  else toc.dispose();
}

onMounted(() => {
  void nextTick(refresh);
});
watch(
  () => [props.articleHtml, props.activeSlug, props.articleTitle],
  () => {
    void nextTick(refresh);
  },
);
onBeforeUnmount(() => toc.dispose());

defineExpose({ refresh, toc });
</script>

<template>
  <div class="lu-docs-frame">
  <div class="lu-docs">
    <aside class="lu-docs-side">
      <slot name="sidebar-head">
        <div class="lu-docs-eyebrow">{{ eyebrow }}</div>
      </slot>
      <nav class="lu-docs-nav">
        <div
          v-for="group in groups"
          :key="group.id"
          class="lu-docs-group"
          :data-advanced="group.advanced ? 'true' : 'false'"
        >
          <div class="lu-docs-group-label">
            <slot name="group-icon" :group="group" />
            <span>{{ group.label }}</span>
          </div>
          <component
            :is="rowTag()"
            v-for="page in group.pages"
            :key="page.slug"
            v-bind="rowBind(group.id, page.slug)"
            class="lu-docs-link"
            :data-active="isActive(group, page.slug) ? 'true' : 'false'"
            :data-advanced="page.advanced ? 'true' : 'false'"
            :aria-current="isActive(group, page.slug) ? 'page' : undefined"
            @click="onNavigate(findDoc(groups, page.slug, group.id))"
          >
            <span class="lu-docs-link-label">{{ page.title }}</span>
            <span v-if="page.badge !== undefined" class="lu-docs-link-badge">{{ page.badge }}</span>
          </component>
        </div>
      </nav>
    </aside>

    <main class="lu-docs-main">
      <article ref="articleRef" class="lu-docs-article">
        <h1 v-if="heading" class="lu-docs-title">{{ heading }}</h1>
        <slot name="article">
          <!-- eslint-disable-next-line vue/no-v-html -->
          <div class="lu-docs-body" v-html="articleHtml" />
        </slot>
      </article>

      <nav v-if="adjacent.prev || adjacent.next" class="lu-docs-pager">
        <component
          :is="rowTag()"
          v-if="adjacent.prev"
          v-bind="rowBind(adjacent.prev.groupId, adjacent.prev.slug)"
          class="lu-docs-pager-link lu-docs-pager-prev"
          @click="onNavigate(adjacent.prev)"
        >
          <span class="lu-docs-pager-dir">{{ prevLabel }}</span>
          <span class="lu-docs-pager-title">{{ adjacent.prev.title }}</span>
        </component>
        <span v-else />
        <component
          :is="rowTag()"
          v-if="adjacent.next"
          v-bind="rowBind(adjacent.next.groupId, adjacent.next.slug)"
          class="lu-docs-pager-link lu-docs-pager-next"
          @click="onNavigate(adjacent.next)"
        >
          <span class="lu-docs-pager-dir">{{ nextLabel }}</span>
          <span class="lu-docs-pager-title">{{ adjacent.next.title }}</span>
        </component>
      </nav>
    </main>

    <aside v-if="showToc" class="lu-docs-toc">
      <slot name="toc" :items="toc.items.value" :active-id="toc.activeId.value">
        <div v-if="toc.items.value.length" class="lu-docs-toc-inner">
          <div class="lu-docs-toc-label">{{ tocLabel }}</div>
          <a
            v-for="item in toc.items.value"
            :key="item.id"
            :href="`#${item.id}`"
            class="lu-docs-toc-link"
            :data-level="item.level"
            :data-active="toc.activeId.value === item.id ? 'true' : 'false'"
            @click="onTocClick(item.id)"
          >{{ item.text }}</a>
        </div>
      </slot>
    </aside>
  </div>
  </div>
</template>
