// src/react/GlassTooltip.tsx
import type { ReactNode } from 'react';
import '../styles/components/glass-tooltip.css';

export interface GlassTooltipProps {
  text: string;
  placement?: 'top' | 'bottom';
  children?: ReactNode;
}

export function GlassTooltip({ text, placement = 'top', children }: GlassTooltipProps) {
  return <span className="lu-tip-wrap">{children}<span className={`lu-tip lu-glass-smoke lu-tip--${placement}`} role="tooltip">{text}</span></span>;
}

// src/components/GlassTooltip.vue
<script setup lang="ts">
import '../styles/components/glass-tooltip.css';
// A hover/focus tooltip on thick glass. Wrap a trigger in the default slot; the
// tip text comes from `text`. Shown on hover and keyboard focus (focus-within),
// so it is reachable without a pointer. Requires `import 'latere-ui/glass'`.
withDefaults(defineProps<{
  text: string;
  placement?: 'top' | 'bottom';
}>(), { placement: 'top' });
</script>

<template>
  <span class="lu-tip-wrap">
    <slot />
    <span class="lu-tip lu-glass-smoke" :class="`lu-tip--${placement}`" role="tooltip">{{ text }}</span>
  </span>
</template>
