// src/react/GlassCheckbox.tsx
// React adapter of GlassCheckbox.vue — a checkbox with a glass check box and a
// label. The native input stays in the DOM for accessibility and keyboard
// support. `value` + `onChange` replace v-model.
import { useId, type ChangeEvent } from 'react';
import '../styles/components/glass-checkbox.css';
import { cx } from './internal';

export interface GlassCheckboxProps {
  value: boolean;
  label?: string;
  disabled?: boolean;
  onChange?: (value: boolean) => void;
}

export function GlassCheckbox({ value, label, disabled = false, onChange }: GlassCheckboxProps) {
  const id = useId();

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    onChange?.(e.target.checked);
  }

  return (
    <label className={cx('lu-check', disabled && 'is-disabled')} htmlFor={id}>
      <input
        id={id}
        type="checkbox"
        className="lu-check-native"
        checked={value}
        disabled={disabled}
        onChange={handleChange}
      />
      <span className="lu-check-box lu-glass-ultrathin" aria-hidden="true">
        <svg className="lu-check-tick" viewBox="0 0 12 12" fill="none">
          <path
            d="M2.5 6.2l2.2 2.2 4.6-4.8"
            stroke="currentColor"
            strokeWidth="1.6"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      </span>
      {label && <span className="lu-check-label">{label}</span>}
    </label>
  );
}

// src/components/GlassCheckbox.vue
<script setup lang="ts">
// A checkbox with a glass check box and a label. v-model binds the boolean; the
// native input stays in the DOM for accessibility and keyboard support.
import { useId } from 'vue';
import '../styles/components/glass-checkbox.css';

withDefaults(defineProps<{
  modelValue: boolean;
  label?: string;
  disabled?: boolean;
}>(), { disabled: false });
const emit = defineEmits<{ (e: 'update:modelValue', v: boolean): void }>();

const id = useId();
function onChange(e: Event) {
  emit('update:modelValue', (e.target as HTMLInputElement).checked);
}
</script>

<template>
  <label class="lu-check" :class="{ 'is-disabled': disabled }" :for="id">
    <input
      :id="id"
      type="checkbox"
      class="lu-check-native"
      :checked="modelValue"
      :disabled="disabled"
      @change="onChange"
    />
    <span class="lu-check-box lu-glass-ultrathin" aria-hidden="true">
      <svg class="lu-check-tick" viewBox="0 0 12 12" fill="none">
        <path d="M2.5 6.2l2.2 2.2 4.6-4.8" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
      </svg>
    </span>
    <span v-if="label" class="lu-check-label">{{ label }}</span>
  </label>
</template>
