// src/react/GlassTabs.tsx
import { useRef, type KeyboardEvent } from 'react';
import type { TabItem } from '../glass/types';
import '../styles/components/glass-tabs.css';
import { cx } from './internal';

export interface GlassTabsProps {
  value: string;
  tabs: TabItem[];
  ariaLabel?: string;
  onChange?: (value: string) => void;
}

/** Tab navigation with automatic selection; the caller renders the active panel. */
export function GlassTabs({ value, tabs, ariaLabel, onChange }: GlassTabsProps) {
  const buttons = useRef<(HTMLButtonElement | null)[]>([]);

  function select(next: string) {
    if (next !== value) onChange?.(next);
  }
  function onKey(event: KeyboardEvent<HTMLButtonElement>, index: number) {
    let next = index;
    if (event.key === 'ArrowRight') next = (index + 1) % tabs.length;
    else if (event.key === 'ArrowLeft') next = (index - 1 + tabs.length) % tabs.length;
    else return;
    event.preventDefault();
    select(tabs[next].value);
    buttons.current[next]?.focus();
  }

  return <div className="lu-tabs" role="tablist" aria-label={ariaLabel}>
    {tabs.map((tab, index) => <button key={tab.value} ref={element => { buttons.current[index] = element; }}
      type="button" role="tab" className={cx('lu-tab', tab.value === value && 'is-active')}
      aria-selected={tab.value === value} tabIndex={tab.value === value ? 0 : -1}
      onClick={() => select(tab.value)} onKeyDown={event => onKey(event, index)}>
      {tab.label}
      {tab.value === value && <span className="lu-tab-ind lu-glass-thin" aria-hidden="true" />}
    </button>)}
  </div>;
}

// src/components/GlassTabs.vue
<script setup lang="ts">
import '../styles/components/glass-tabs.css';
// A tab strip with a sliding glass indicator. Full ARIA tablist semantics with
// arrow-key roving focus. v-model binds the active tab value; render the active
// panel yourself (this is navigation, not a container).
// Requires `import 'latere-ui/glass'`.
import { ref } from 'vue';
import type { TabItem } from '../glass/types';

const props = defineProps<{
  modelValue: string;
  tabs: TabItem[];
  ariaLabel?: string;
}>();
const emit = defineEmits<{ (e: 'update:modelValue', v: string): void }>();

const btns = ref<HTMLButtonElement[]>([]);

function select(v: string) {
  if (v !== props.modelValue) emit('update:modelValue', v);
}
function onKey(e: KeyboardEvent, i: number) {
  const n = props.tabs.length;
  let next = i;
  if (e.key === 'ArrowRight') next = (i + 1) % n;
  else if (e.key === 'ArrowLeft') next = (i - 1 + n) % n;
  else return;
  e.preventDefault();
  select(props.tabs[next].value);
  btns.value[next]?.focus();
}
</script>

<template>
  <div class="lu-tabs" role="tablist" :aria-label="ariaLabel">
    <button
      v-for="(tab, i) in tabs"
      :key="tab.value"
      ref="btns"
      type="button"
      role="tab"
      class="lu-tab"
      :class="{ 'is-active': tab.value === modelValue }"
      :aria-selected="tab.value === modelValue"
      :tabindex="tab.value === modelValue ? 0 : -1"
      @click="select(tab.value)"
      @keydown="onKey($event, i)"
    >
      {{ tab.label }}
      <span v-if="tab.value === modelValue" class="lu-tab-ind lu-glass-thin" aria-hidden="true" />
    </button>
  </div>
</template>
