// src/react/LocaleMenu.tsx
// The language control: a quiet globe button that opens the offered languages
// on a solid menu surface, each named in its own language, with a check on
// the current one. Built on GlassPopover and GlassMenu, like ThemeMenu.
// Presentational: the host owns the locale.
import type { LocaleOption } from '../i18n/footer';
import { DEFAULT_LOCALE_OPTIONS, GLOBE_ICON, localeMenuItems, localeTriggerLabel } from '../components/preferenceMenus';
import { GlassPopover } from './GlassPopover';
import { GlassMenu } from './GlassMenu';
import { cx } from './internal';
import '../styles/components/preference-menu.css';

export interface LocaleMenuProps {
  /** Current locale code. */
  locale: string;
  /** Called with the locale the reader picked. */
  onLocaleChange?: (locale: string) => void;
  /** Languages offered. Defaults to English and Chinese. */
  locales?: LocaleOption[];
  /** Name of the menu and prefix of the trigger's accessible name. */
  label?: string;
  placement?: 'bottom-start' | 'bottom-end' | 'top-start' | 'top-end';
  /** Extra class on the root, for host placement. */
  className?: string;
}

export function LocaleMenu({
  locale,
  onLocaleChange,
  locales = DEFAULT_LOCALE_OPTIONS,
  label = 'Language',
  placement = 'bottom-end',
  className,
}: LocaleMenuProps) {
  return (
    <GlassPopover
      className={cx('lu-pref lu-locale-menu', className)}
      placement={placement}
      surface="solid"
      trigger={({ open, id }) => (
        <button
          type="button"
          className="lu-pref-trigger"
          aria-haspopup="menu"
          aria-expanded={open}
          aria-controls={open ? id : undefined}
          aria-label={localeTriggerLabel(locale, locales, label)}
          title={label}
        >
          <span className="lu-pref-icon" dangerouslySetInnerHTML={{ __html: GLOBE_ICON }} />
        </button>
      )}
    >
      {({ close }) => (
        <GlassMenu
          items={localeMenuItems(locale, locales)}
          label={label}
          autofocus
          onSelect={value => { onLocaleChange?.(value); close(); }}
        />
      )}
    </GlassPopover>
  );
}

// src/components/LocaleMenu.vue
<script setup lang="ts">
import '../styles/components/preference-menu.css';
// The language control: a quiet globe button that opens the offered languages
// on a solid menu surface, each named in its own language, with a check on
// the current one. Built on GlassPopover and GlassMenu, like ThemeMenu.
// Presentational: the host owns the locale.
import { computed } from 'vue';
import GlassPopover from './GlassPopover.vue';
import GlassMenu from './GlassMenu.vue';
import type { LocaleOption } from '../i18n/footer';
import { DEFAULT_LOCALE_OPTIONS, GLOBE_ICON, localeMenuItems, localeTriggerLabel } from './preferenceMenus';

const props = withDefaults(defineProps<{
  /** Current locale code. */
  locale: string;
  /** Languages offered. Defaults to English and Chinese. */
  locales?: LocaleOption[];
  /** Name of the menu and prefix of the trigger's accessible name. */
  label?: string;
  placement?: 'bottom-start' | 'bottom-end' | 'top-start' | 'top-end';
}>(), { locales: () => DEFAULT_LOCALE_OPTIONS, label: 'Language', placement: 'bottom-end' });
const emit = defineEmits<{ 'update:locale': [string] }>();

const items = computed(() => localeMenuItems(props.locale, props.locales));
function choose(value: string, close: () => void) {
  emit('update:locale', value);
  close();
}
</script>

<template>
  <GlassPopover class="lu-pref lu-locale-menu" :placement="placement" surface="solid">
    <template #trigger="{ open, id }">
      <button
        type="button"
        class="lu-pref-trigger"
        aria-haspopup="menu"
        :aria-expanded="open"
        :aria-controls="open ? id : undefined"
        :aria-label="localeTriggerLabel(locale, locales, label)"
        :title="label"
      ><span class="lu-pref-icon" v-html="GLOBE_ICON" /></button>
    </template>
    <template #default="{ close }">
      <GlassMenu :items="items" :label="label" autofocus @select="choose($event, close)" />
    </template>
  </GlassPopover>
</template>
