// src/components/GlassPanel.vue
<script setup lang="ts">
// A content card: a regular-tier glass surface with comfortable padding. Inner
// regions that must stay crisp (code, media) should opt out of glass and paint
// an opaque background themselves — glass is chrome, not content.
import GlassSurface from './GlassSurface.vue';
import type { GlassTier } from '../glass/useGlass';
import '../styles/components/glass-panel.css';

withDefaults(defineProps<{
  /** Override the tier if a panel needs a thinner/thicker material. */
  tier?: GlassTier;
  /** Drop the default padding (for panels that own their own layout). */
  flush?: boolean;
}>(), {
  tier: 'regular',
  flush: false,
});
</script>

<template>
  <GlassSurface :tier="tier" class="lu-panel" :class="{ 'lu-panel-flush': flush }">
    <slot />
  </GlassSurface>
</template>

// src/react/GlassPanel.tsx
// GlassPanel: a content card, a regular-tier glass
// surface with comfortable padding.
import type { ReactNode } from 'react';
import '../styles/components/glass-panel.css';
import { GlassSurface, type GlassTier } from './GlassSurface';
import { cx } from './internal';

export interface GlassPanelProps {
  /** Override the tier if a panel needs a thinner/thicker material. */
  tier?: GlassTier;
  /** Drop the default padding (for panels that own their own layout). */
  flush?: boolean;
  children?: ReactNode;
}

export function GlassPanel({ tier = 'regular', flush = false, children }: GlassPanelProps) {
  return (
    <GlassSurface tier={tier} className={cx('lu-panel', flush && 'lu-panel-flush')}>
      {children}
    </GlassSurface>
  );
}
