// src/components/GlassSpinner.vue
<script setup lang="ts">
// An indeterminate loading spinner. Announces itself to assistive tech; slows
// (never stops) under reduced motion so it still reads as "busy".
import '../styles/components/glass-spinner.css';

withDefaults(defineProps<{
  size?: number;
  label?: string;
}>(), { size: 20, label: 'Loading' });
</script>

<template>
  <span
    class="lu-spinner"
    role="status"
    :aria-label="label"
    :style="{ width: `${size}px`, height: `${size}px` }"
  />
</template>

// src/react/GlassSpinner.tsx
// GlassSpinner: an indeterminate loading spinner.
// Announces itself to assistive tech; slows (never stops) under reduced motion.
import '../styles/components/glass-spinner.css';

export interface GlassSpinnerProps {
  size?: number;
  label?: string;
}

export function GlassSpinner({ size = 20, label = 'Loading' }: GlassSpinnerProps) {
  return (
    <span
      className="lu-spinner"
      role="status"
      aria-label={label}
      style={{ width: `${size}px`, height: `${size}px` }}
    />
  );
}
