// src/components/GlassConfirmHost.vue
<script setup lang="ts">
import '../styles/components/glass-confirm-host.css';
// Host for the imperative confirm() service. Mount ONCE near the app root:
//   <GlassConfirmHost />
// Renders the active confirm dialog on a GlassModal. Requires 'latere-ui/glass'.
import { computed } from 'vue';
import GlassModal from './GlassModal.vue';
import GlassButton from './GlassButton.vue';
import { currentConfirm, resolveConfirm } from '../glass/confirm';

const open = computed(() => currentConfirm.current !== null);
const c = computed(() => currentConfirm.current);
</script>

<template>
  <GlassModal
    :open="open"
    :title="c?.title"
    :close-on-scrim="false"
    width="26rem"
    layer="confirm"
    @close="resolveConfirm(false)"
  >
    <p class="lu-confirm-msg">{{ c?.message }}</p>
    <template #footer>
      <GlassButton variant="ghost" size="sm" @click="resolveConfirm(false)">
        {{ c?.cancelText ?? 'Cancel' }}
      </GlassButton>
      <GlassButton
        :variant="c?.danger ? 'danger' : 'primary'"
        size="sm"
        @click="resolveConfirm(true)"
      >
        {{ c?.confirmText ?? 'Confirm' }}
      </GlassButton>
    </template>
  </GlassModal>
</template>

// src/react/GlassConfirmHost.tsx
import { useSyncExternalStore } from 'react';
import { confirmStore, getServerConfirm, resolveConfirm } from '../glass/confirmCore';
import { GlassModal } from './GlassModal';
import { GlassButton } from './GlassButton';
import '../styles/components/glass-confirm-host.css';

/** Mount once near the app root to render queued confirm() requests. */
export function GlassConfirmHost() {
  const { current: c } = useSyncExternalStore(confirmStore.subscribe, confirmStore.getSnapshot, getServerConfirm);
  return (
    <GlassModal
      open={c !== null}
      title={c?.title}
      closeOnScrim={false}
      width="26rem"
      layer="confirm"
      onClose={() => resolveConfirm(false)}
      footer={<>
        <GlassButton variant="ghost" size="sm" onClick={() => resolveConfirm(false)}>
          {c?.cancelText ?? 'Cancel'}
        </GlassButton>
        <GlassButton variant={c?.danger ? 'danger' : 'primary'} size="sm" onClick={() => resolveConfirm(true)}>
          {c?.confirmText ?? 'Confirm'}
        </GlassButton>
      </>}
    >
      <p className="lu-confirm-msg">{c?.message}</p>
    </GlassModal>
  );
}
